apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-p4d
  region: PLACEHOLDER_AWS_REGION
  version: "1.33"

# List availability zones where cluster subnets will be created
availabilityZones:
  - PLACEHOLDER_AZ1
  - PLACEHOLDER_AZ2

# Substitute vpc and subnet ids below
# if you want a VPC to be created, commentout vpc related lines
vpc:
  id: PLACEHOLDER_VPC_ID
  subnets:
    private:
      private-one:
        id: PLACEHOLDER_SUBNET_PRIVATE_1
      private-two:
        id: PLACEHOLDER_SUBNET_PRIVATE_2
    public:
      public-one:
        id: PLACEHOLDER_SUBNET_PUBLIC_1
      public-two:
        id: PLACEHOLDER_SUBNET_PUBLIC_2  

iam:
  withOIDC: true

# EKS-managed node group(s)
managedNodeGroups:
  # Nodegroup for system pods
  - name: sys
    instanceType: c5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true

  # GPU nodegroup
  # List availability zones where instances in from this nodegroup will be launched
  # Update capacityReservationID with your own if you have a capacity reservation
  # Update desiredCapacity to the number of instances you want to launch
  - name: p4d
    instanceType: p4d.24xlarge
    instancePrefix: p4d
    privateNetworking: true
    efaEnabled: true
    minSize: 0
    desiredCapacity: 2
    maxSize: 4
    availabilityZones: ["PLACEHOLDER_AZ"]
    capacityReservation:
      capacityReservationTarget:
        capacityReservationID: "cr-xxxxxxxxxx"
    # Utilize the local instance store volume(s)
    overrideBootstrapCommand: |
      apiVersion: node.eks.aws/v1alpha1
      kind: NodeConfig
      spec:
        instance:
          localStorage:
            strategy: RAID0
    iam:
      withAddonPolicies:
        autoScaler: true
        cloudWatch: true
        ebs: true
        fsx: true

addons:
# vpc-cni, coredns, and kube-proxy addons are installed by default by EKS
  - name: aws-ebs-csi-driver
    wellKnownPolicies:      # add IAM and service account
      ebsCSIController: true
  - name: eks-node-monitoring-agent
    resolveConflicts: overwrite
  - name: amazon-cloudwatch-observability
    resolveConflicts: overwrite
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/CloudWatchFullAccess

